# Local IspellDict: en
#+SPDX-FileCopyrightText: 2020 Maximilian Harl
#+SPDX-License-Identifier: CC-BY-SA-4.0

#+STARTUP: showeverything
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./reveal.js/css/theme/index.css" />
#+TITLE: Open Educational Resource (OER) presentations for an introductory course in computer science
#+AUTHOR: Maximilian Victor Harl
#+OPTIONS: html-style:nil
#+OPTIONS: toc:nil
#+KEYWORDS: computer science, OER, open educational resources, creative commons, free and open license, presentations, slides, JiTT, just-in-time teaching, FAU, Friedrich-Alexander University, DISS, Chair of Digital Industrial Service Systems
#+DESCRIPTION: Collection of OER presentations for an introductroy university course on computer science

* What is this?
This page collects
[[https://en.wikipedia.org/wiki/Open_educational_resources][OER]]
presentations (HTML slides with embedded audio and PDF variants, available under
[[https://en.wikipedia.org/wiki/Free_license][free]] and open
[[https://creativecommons.org/use-remix/cc-licenses/][Creative Commons licenses]]
in Section [[#presentations]], preceded by usage hints in
Section [[#hints]])
for an indtroductory course on computer science as part of the module
[[https://www.is.rw.fau.de/lehre/veranstaltungen/intro-to-cs/][Introduction to Computer Science]]
for first semester students in the Master degree program in
[[http://iis.fau.de/][International Information Systems]]
at the [[https://www.fau.de/][Friedrich-Alexander University Erlangen-Nuremberg, Germany]].
Some background concerning the origin of this project and the adopted
teaching and learning strategy is explained in its [[https://github.com/EinGartenzwerg/EinGartenzwerg.github.io/blob/master/README.md][README]].

If you are teaching or learning computer science, feel free to
use, share, and adapt my presentations.  As usual for projects on GitHub/GitLab,
you can open [[https://help.github.com/en/enterprise/2.15/user/articles/creating-an-issue][issues]]
to report bugs or suggest improvements, ideally
with [[https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request][pull requests]].
The document
[[https://github.com/EinGartenzwerg/EinGartenzwerg.github.io/blob/master/CONTRIBUTING.org][CONTRIBUTING]]
contains some pointers for contributors.

Students in the Master's degree International Information Systems have no prior experience with programming or computer science. Therefore there are no prerequisites for "Introduction to Computer Science".

*Learning objectives*: After taking this course, students will be able to
- recognise and deduce patterns among programming problems
- decompose problems into parts and compose solutions thereto
- operate at multiple levels of abstraction
- infer from first principles how computer systems work
- assess correctness, design and style of code
- teach yourself new programming languages
- read code documentation and draw conclusions from specifications
- describe symptoms of problems precisely and ask questions clearly
- test solutions to problems, find faults, and identify corner cases

* Presentations
  :PROPERTIES:
  :CUSTOM_ID: presentations
  :END:
   *Note*: OER presentations (HTML slides and PDF documents) linked
   here are generated automatically from
   their source files (with the FLOSS software
   [[https://gitlab.com/oer/emacs-reveal][emacs-reveal]]).
   Presentations and source files are published under the Creative
   Commons license
   [[https://creativecommons.org/licenses/by-sa/4.0/][CC BY-SA 4.0]].
   Files are updated throughout the term (and thereafter).
   The PDF versions provided below are generated via LaTeX from Org
   source files.

   - Self-study presentations
     - [[file:IntroCS_overview.org][*Overview of Introduction to Computer Science*]]

   For offline work (also on mobile devices), you can
   [[https://gitlab.com/EinGartenzwerg/EinGartenzwerg-github-io/pipelines][download the results of the latest pipeline execution on GitLab]]
   or clone the [[https://gitlab.com/EinGartenzwerg/EinGartenzwerg-github-io][source repository including all necessary resources]]
   and generate presentations yourself.


* Source code and licenses
The structure of this repository and the hints for reveal.js are based on the [[https://gitlab.com/oer][Open Educational Ressources (OER) ressources of Jens Lechtenbörger]] and his by [[https://gitlab.com/oer/emacs-reveal][emacs-reveal]] plugin.

#+MACRO: gitlablink [[https://gitlab.com/EinGartenzwerg/IntroCS/][$1]]
#+INCLUDE: "~/.emacs.d/oer-reveal-org/source-code-licenses.org"
